version: '3.7'

services:
  php-apache-xdebug-raw:
    build:
      context: ./dockerfile_folder
    ports:
      - 80:80
    volumes:
      - "./src:/var/www/html"
    environment:
      # XDEBUG_CONFIG: remote_host=host.docker.internal
      # will not work in linux. need to use $hostname in terminal to find hostname. Mine is ubuntu.
      XDEBUG_CONFIG: remote_host=ubuntu